# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AMP Studio
tel: 01782 853973
email: enquiries@amp.studio
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: https://www.instagram.com/ampstudiouk/
twitter_username: https://twitter.com/ampstudiouk
facebook_username: https://www.facebook.com/Ampstudiouk/
linkedin_username: https://www.linkedin.com/company/18133628/

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed

# Deafult settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /:categories/:year/:title/
      layout: "blog-post"
  -
    scope:
      path: "portfolio"
      type: "posts"
    values:
      layout: "portfolio-post"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Exclude dev files
exclude: ["_dev",
            "gulpfile.js",
            "node_modules",
            "package.json",
            "package-lock.json",
            "analytics.js",
            "Gemfile",
            "Gemfile.lock"]

# Include font assets
assets:
   sources:
     -_assets/fonts

# Sitemap Generator
url: "https://amp.studio" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap